export type { AppContext, AppFocus, WhenPredicate, WhenPredicateMap } from './types'
export { defaultWhenPredicates } from './predicates'
export { whenTrue } from './eval'
export { buildAppContext, resolveAppFocus } from './focus'
export { WHEN_LABELS } from './labels'
