/** UI copy for named when-predicates. Predicate code stays the source of truth. */
export const WHEN_LABELS: Record<string, string> = {
  always: 'Always',
  moveInProgress: 'While Move is in progress',
  moveNotInProgress: 'While Move is not in progress',
  resizeInProgress: 'While Resize is in progress',
  resizeNotInProgress: 'While Resize is not in progress',
  connectionDragInProgress: 'While dragging a connection',
  noToolInProgress: 'No tool in progress',
  graphFocused: 'Editable graph focused',
  graphEditable: 'Editable graph',
  canBeginGrabMove: 'Editable graph, has selection, no tool in progress',
  canBeginResize: 'Editable graph, has selection, no tool in progress',
  canNudgeSelection: 'Has selection, not resizing',
  canDeleteSelection: 'Editable graph, has selection, no tool in progress',
  canFocusAppTool: 'Graph loaded, no tool in progress, editable graph',
  toolIsMove: 'Only Move tool active',
  toolIsResize: 'Only Resize tool active',
  canPickConnectionEndpoint: 'Add Connection focused, has selection',
  canCopySelection: 'Editable graph, has selection, no tool in progress',
  canDeselectAll: 'Has selection, no tool in progress',
  canSelectChildren: 'Editable graph, has selection, no tool in progress',
  canPasteNodes: 'Editable graph, graph loaded, no tool in progress',
  canSaveProject: 'Graph loaded',
}
