/**
 * Singleton animgraph simulation runtime (clock, runners, board, libraries).
 * Created once for the app; UI (SimPanel, windows) imports from here.
 */
import { useAnimgraphSim } from '../composables/useAnimgraphSim'

export const animgraphSim = useAnimgraphSim()

export const {
  enabled: simEnabled,
  active: simActive,
  /** Active-diagram view of snapshotsByDiagram (computed). */
  snapshot: simSnapshot,
  snapshotsByDiagram: simSnapshotsByDiagram,
  snapshotForDiagram: simSnapshotForDiagram,
  getSkeletonViewPose: simGetSkeletonViewPose,
  discovered: simDiscovered,
  eventDraft: simEventDraft,
  featureDrafts: simFeatureDrafts,
  vectorFeatureDrafts: simVectorFeatureDrafts,
  quatFeatureDrafts: simQuatFeatureDrafts,
  boolFeatureDrafts: simBoolFeatureDrafts,
  floatVarDrafts: simFloatVarDrafts,
  vectorVarDrafts: simVectorVarDrafts,
  quatVarDrafts: simQuatVarDrafts,
  boolVarDrafts: simBoolVarDrafts,
  intVarDrafts: simIntVarDrafts,
  tagValueDrafts: simTagValueDrafts,
  entityTagDrafts: simEntityTagDrafts,
  wrapperWeightDrafts: simWrapperWeightDrafts,
  clipStats: simClipStats,
  clipNames: simClipNames,
  setupEntries: simSetupEntries,
  animDbStats: simAnimDbStats,
  animDatabases: simAnimDatabases,
  rigEntries: simRigEntries,
  activeRigBones: simActiveRigBones,
  activeRigParts: simActiveRigParts,
  clipPoseSets: simClipPoseSets,
  getClipGlbInfo: simGetClipGlbInfo,
  listGlbAnimNames: simListGlbAnimNames,
  draftFeatureValue: simDraftFeatureValue,
  draftVectorFeatureValue: simDraftVectorFeatureValue,
  draftQuatFeatureValue: simDraftQuatFeatureValue,
  draftBoolFeatureValue: simDraftBoolFeatureValue,
  getClip: simGetClip,
  lookupClip: simLookupClip,
  isClipActive: simIsClipActive,
  listClipSets: simListClipSets,
  loadAnimsetJson: simLoadAnimsetJson,
  loadAnimsetGlb: simLoadAnimsetGlb,
  clearAnimsetGlb: simClearAnimsetGlb,
  loadClipLibraryJson: simLoadClipLibraryJson,
  clearClipLibrary: simClearClipLibrary,
  clearClipPoseLibrary: simClearClipPoseLibrary,
  loadRigJson: simLoadRigJson,
  removeRig: simRemoveRig,
  setActiveRig: simSetActiveRig,
  clearRigLibrary: simClearRigLibrary,
  stackCaptureHandleIds: simStackCaptureHandleIds,
  getDerivedPoseStats: simGetDerivedPoseStats,
  sampleWarningsEnabled: simSampleWarningsEnabled,
  setSampleWarningsEnabled: simSetSampleWarningsEnabled,
  updateWarningsEnabled: simUpdateWarningsEnabled,
  setUpdateWarningsEnabled: simSetUpdateWarningsEnabled,
  setStackCaptureHandleIds: simSetStackCaptureHandleIds,
  loadAnimDatabaseJson: simLoadAnimDatabaseJson,
  loadAnimDatabaseLibraryJson: simLoadAnimDatabaseLibraryJson,
  clearAnimDatabaseLibrary: simClearAnimDatabaseLibrary,
  removeAnimDatabase: simRemoveAnimDatabase,
  updateSetupEntry: simUpdateSetupEntry,
  removeSetupEntry: simRemoveSetupEntry,
  exportCompactClipLibrary: simExportCompactClipLibrary,
  exportCompactAnimDatabaseLibrary: simExportCompactAnimDatabaseLibrary,
  getProjectSimResources: simGetProjectSimResources,
  getCachedClipPoseCompactText: simGetCachedClipPoseCompactText,
  applyProjectSimResources: simApplyProjectSimResources,
  play: simPlay,
  pause: simPause,
  toggle: simToggle,
  step: simStep,
  reset: simReset,
  activate: simActivate,
  deactivate: simDeactivate,
  toggleActive: simToggleActive,
  setSpeed: simSetSpeed,
  fireExternal: simFireExternal,
  fireAnimEvent: simFireAnimEvent,
  fireAnimEnd: simFireAnimEnd,
  setFloatVar: simSetFloatVar,
  setVectorVar: simSetVectorVar,
  setVectorVarAxis: simSetVectorVarAxis,
  draftVectorVarValue: simDraftVectorVarValue,
  setQuatVar: simSetQuatVar,
  setQuatVarAxis: simSetQuatVarAxis,
  draftQuatVarValue: simDraftQuatVarValue,
  setBoolVar: simSetBoolVar,
  setIntVar: simSetIntVar,
  setTagValue: simSetTagValue,
  setEntityTag: simSetEntityTag,
  removeEntityTag: simRemoveEntityTag,
  setWrapperWeight: simSetWrapperWeight,
  setFeature: simSetFeature,
  setBoolFeature: simSetBoolFeature,
  setVectorFeature: simSetVectorFeature,
  setVectorFeatureAxis: simSetVectorFeatureAxis,
  setQuatFeature: simSetQuatFeature,
  setQuatFeatureAxis: simSetQuatFeatureAxis,
  rebind: simRebind,
  dispose: disposeAnimgraphSim,
} = animgraphSim
